"""drop cafe owner and cafe schedul

Revision ID: 46b09c30df76
Revises: 95b98dcdb9f0
Create Date: 2026-01-03 18:11:16.515863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b09c30df76'
down_revision: Union[str, Sequence[str], None] = '95b98dcdb9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe_schedul',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weekday', sa.Enum('all', 'saturday', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', name='schedul_days'), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('start_hour', sa.Time(), nullable=False),
    sa.Column('stop_hour', sa.Time(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe_schedul_cafe_id'), 'cafe_schedul', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_cafe_schedul_id'), 'cafe_schedul', ['id'], unique=False)
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_token_jti'), 'revoked_token', ['jti'], unique=False)
    op.add_column('cafe', sa.Column('provider', sa.String(length=200), nullable=False))
    op.drop_constraint(op.f('cafe_owner_id_fkey'), 'cafe', type_='foreignkey')
    op.drop_column('cafe', 'owner_id')
    op.alter_column('cafe_comment', 'rate',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cafe_comment', 'rate',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('cafe', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cafe_owner_id_fkey'), 'cafe', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('cafe', 'provider')
    op.drop_index(op.f('ix_revoked_token_jti'), table_name='revoked_token')
    op.drop_table('revoked_token')
    op.drop_index(op.f('ix_cafe_schedul_id'), table_name='cafe_schedul')
    op.drop_index(op.f('ix_cafe_schedul_cafe_id'), table_name='cafe_schedul')
    op.drop_table('cafe_schedul')
    # ### end Alembic commands ###
