"""phone_approved to user

Revision ID: 87c1e6cf492a
Revises: ba7a16be8342
Create Date: 2025-12-09 17:55:05.476210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c1e6cf492a'
down_revision: Union[str, Sequence[str], None] = 'ba7a16be8342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_approved')
    # ### end Alembic commands ###
