"""cafe provider

Revision ID: 95b98dcdb9f0
Revises: 9a69622dd795
Create Date: 2026-01-03 02:15:32.979833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b98dcdb9f0'
down_revision: Union[str, Sequence[str], None] = '9a69622dd795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafe_comment', sa.Column('provider', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafe_comment', 'provider')
    # ### end Alembic commands ###
