"""cafe

Revision ID: 9a69622dd795
Revises: 88b2b3739f1e
Create Date: 2025-12-31 20:40:41.720047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '9a69622dd795'
down_revision: Union[str, Sequence[str], None] = '88b2b3739f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('aboute', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe_id'), 'cafe', ['id'], unique=False)
    op.create_table('cafe_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'employee', name='comment_role'), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe_comment_cafe_id'), 'cafe_comment', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_cafe_comment_id'), 'cafe_comment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cafe_comment_id'), table_name='cafe_comment')
    op.drop_index(op.f('ix_cafe_comment_cafe_id'), table_name='cafe_comment')
    op.drop_table('cafe_comment')
    op.drop_index(op.f('ix_cafe_id'), table_name='cafe')
    op.drop_table('cafe')
    # ### end Alembic commands ###
